### ISSUE TITLE
Using require command fails on a clean system

### ISSUE THREAD

**Issue by a1exsh** [zalando-incubator/zalando-aws-cli#17]
The `require` subcommand on a clean system fails like this:
```
$ zaws re my_account
Enter credentials service URL: https://aws-credentials.stups.zalan.do
Traceback (most recent call last):
  File "/home/oshulgin/.local/bin/zaws", line 11, in <module>
    sys.exit(main())
  File "/home/oshulgin/.local/lib/python3.5/site-packages/zalando_aws_cli/cli.py", line 331, in main
    cli()
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/zalando_aws_cli/cli.py", line 138, in require
    account_name, role_name = get_account_name_role_name(ctx.obj, account_role_or_alias)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/zalando_aws_cli/cli.py", line 74, in get_account_name_role_name
    profiles = get_profiles(config['service_url'])
KeyError: 'service_url'
```

The next run succeeds though, because `service_url` is stored in the config file despite the error:
```
$ cat ~/.config/zalando-aws-cli/zalando-aws-cli.yaml
{service_url: 'https://aws-credentials.stups.zalan.do'}
```

Related: #16

**Comment by tuxlife** [comment]
fixed in version v1.1.6
